name: weather_app
description: Weather app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: 3.3.9

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  hooked_bloc: 1.2.1
  flutter_hooks: 0.18.5+1
  get_it: 7.2.0
  injectable: 2.0.1
  chopper: 6.0.0
  freezed_annotation: 2.2.0
  json_annotation: 4.7.0
  go_router: 5.2.0
  google_fonts: 3.0.1
  flutter_svg: 1.1.6
  rxdart: 0.27.7
  cupertino_icons: 1.0.0
  collection: 1.16.0
  intl: 0.17.0
  shared_preferences: 2.0.17
  easy_localization: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.2
  freezed: 2.2.1
  flutter_lints: 2.0.0
  json_serializable: 6.5.4
  go_router_builder: 1.0.15
  injectable_generator: 2.0.1
  chopper_generator: 6.0.0
  mockito: 5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/backgrounds/
    - assets/images/symbols/
    - assets/translations/
